"""
Hybrid and Semantic Search Core Library
Provides libraries for document ingestion as well as the implementations of semantic and hybrid search.
"""

import importlib.metadata

try:
    # This reads the version directly from the installed package metadata
    # generated by pyproject.toml
    __version__ = importlib.metadata.version("search_core")
except importlib.metadata.PackageNotFoundError:
    # Fallback if the package is imported without being formally installed
    # (e.g., during some raw local scripting)
    __version__ = "unknown"

from search_core.interfaces import (
    AsyncVectorStore,
    DenseEncoder,
    SparseEncoder,
    VectorItem,
    VectorStore,
)
from search_core.models import (
    Document,
    EmbeddedDocument,
    EmbeddedQuery,
    SearchConfig,
    SearchMode,
    SearchQuery,
    SearchResponse,
    SearchResult,
    SparseVector,
)
from search_core.stores import QdrantEmbeddingStore, QdrantStoreConfig

__all__ = [
    "__version__",
    # Models
    "Document",
    "EmbeddedDocument",
    "EmbeddedQuery",
    "SearchConfig",
    "SearchMode",
    "SearchQuery",
    "SearchResponse",
    "SearchResult",
    "SparseVector",
    # Interfaces
    "DenseEncoder",
    "SparseEncoder",
    "VectorItem",
    "VectorStore",
    "AsyncVectorStore",
    # Stores
    "QdrantEmbeddingStore",
    "QdrantStoreConfig",
]
